app = "aimly-backend"
primary_region = "ams"

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true

[env]
SPRING_PROFILES_ACTIVE = "prod"